language: r
r: bioc-devel

cache: packages

before_install:
  - tlmgr install tcolorbox
  - tlmgr install bera
  - tlmgr install nowidow
  - tlmgr install parnotes
  - tlmgr install marginfix

# safelist
branches:
  only:
  - master
  - development

script:
  - Rscript -e "library(testthat); invisible(source_dir('./', env=globalenv())); test_dir('tests/testthat'); test_dir('tests/testthat', reporter='stop')"

